.PHONY: clean All

All:
	@echo "==========Building project:[ FromGlobalVariables - Debug ]=========="
	@cd "FromGlobalVariables" && "$(MAKE)" -f  "FromGlobalVariables.mk"
clean:
	@echo "==========Cleaning project:[ FromGlobalVariables - Debug ]----------"
	@cd "FromGlobalVariables" && "$(MAKE)" -f  "FromGlobalVariables.mk" clean
